#!/usr/bin/env python3
"""Keep the README's status table agreeing with what the tree can actually do.

A README's status section is the first thing a reader uses to decide whether to
install a tool, and it is a set of machine-decidable facts written as prose. So
it decays the way every hand-kept copy decays, and it decays silently: nothing
re-reads it when the thing it describes changes.

This repo already has the answer for a list -- `gates.py` derives the CLAUDE.md
table from `GATES` and fails until they agree. This is the same shape for the
README, and the same argument applies: a status claim that can go stale without
anyone noticing is worse than no claim, because it reads as authoritative.

What it asserts:

  * the commands the binary answers, agreed three ways -- the `case` arms in
    main.go, the `usage` text beside them, and the built binary's own behaviour.
    Two hand-kept copies of one list is the drift shape one level down;
  * which of this module's packages the shipped binary can reach, from
    `go list -deps ./cmd/spill-guard`. This is the fact that decayed: code can
    be written, tested and gated while nothing imports it, and every gate stays
    green because unreachable code is still correct code;
  * whether the shipped ruleset and the hook wiring exist on disk;
  * that the generated block in README.md matches all of the above.

Two modes, as `gates.py` has. With no argument it rewrites the block. `--check`
asserts instead and exits 1 listing every disagreement, so one run reports the
whole tree rather than the first thing wrong.

Needs Go on PATH, because the reachability question is one only the toolchain
can answer and a regex over import lines would be a second parser that disagrees
with the first. `check-launcher.py` already requires Go for the same class of
reason.
"""

import re
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "README.md"
MAIN = ROOT / "cmd" / "spill-guard" / "main.go"
MODULE = "github.com/karlkfi/claude-spill-guard"

# The width the rest of README.md wraps at.
WIDTH = 79

BEGIN = ("<!-- status:begin -- generated by `make status`; "
         "derived from the tree, not hand-kept -->")
END = "<!-- status:end -->"

# The two files whose presence a reader is really asking about. Both are named
# in docs/design/README.md's layout block and neither exists yet.
RULESET = ROOT / "rules" / "spill-guard.json"
WIRING = ROOT / "hooks" / "hooks.json"

# A command the binary must NOT recognise. It is the positive control on the
# probe below: if `unknown` is reported for this too, the probe can tell a
# handled command from an unhandled one. Without it a probe that always says
# "handled" would confirm every command in the list and mean nothing.
NOT_A_COMMAND = "definitely-not-a-subcommand"

CASE = re.compile(r'^\s*case\s+"([a-z][a-z0-9-]*)":', re.M)
USAGE_LINE = re.compile(r"^\s{2}([a-z][a-z0-9-]*)\s{2,}\S", re.M)


def go(*args):
    """`go` with args, or exit saying which call failed and why."""
    done = subprocess.run(("go",) + args, capture_output=True, text=True,
                          cwd=ROOT, check=False)
    if done.returncode != 0:
        sys.exit(f"status: `go {' '.join(args)}` exited {done.returncode}, so "
                 f"nothing below could be derived -- {done.stderr.strip()!r}")
    return done.stdout.split()


def module_packages(args):
    """The packages of this module in a `go list` result, shortened."""
    return sorted(p[len(MODULE) + 1:] for p in go(*args)
                  if p == MODULE or p.startswith(MODULE + "/"))


def declared_commands(findings):
    """Commands main.go dispatches, checked against the usage text beside it.

    Two copies, so they can disagree: a `case` arm with no usage line is a
    command nobody is told about, and a usage line with no arm is a command the
    binary refuses. Both are worth failing on, and neither is visible from
    running the binary with one argument.
    """
    src = MAIN.read_text(encoding="utf-8")
    cases = set(CASE.findall(src))

    block = re.search(r"const usage = `(.*?)`", src, re.S)
    if block is None:
        findings.append(f"{MAIN.relative_to(ROOT)} has no `const usage` block, "
                        f"so the command list has only one copy and nothing "
                        f"cross-checks the dispatch")
        return sorted(cases)
    listed = set(USAGE_LINE.findall(block.group(1)))

    for name in sorted(cases - listed):
        findings.append(f"main.go dispatches {name!r} and its usage text does "
                        f"not name it, so the binary answers a command nobody "
                        f"is told about")
    for name in sorted(listed - cases):
        findings.append(f"main.go's usage text names {name!r} and no `case` "
                        f"arm handles it, so the binary refuses a command it "
                        f"advertises")
    return sorted(cases | listed)


def probe(commands, findings):
    """Run the built binary and keep the commands it really answers.

    The source is a claim about behaviour and this is the behaviour. The
    control runs first: a command the binary cannot know must come back
    unhandled, or the probe cannot tell the two apart and its agreement below
    would be worth nothing.
    """
    binary = ROOT / ".status-probe" / "spill-guard"
    binary.parent.mkdir(exist_ok=True)
    try:
        go("build", "-o", str(binary), "./cmd/spill-guard")

        def unknown(name):
            # stdin from /dev/null, because `hook` reads a payload from it and
            # would otherwise block on whatever this script inherited. A
            # terminal or an open pipe never reaches EOF, so the probe hangs
            # rather than failing -- and a CI `run:` step, whose stdin is
            # already /dev/null, would never show it.
            done = subprocess.run([str(binary), name], capture_output=True,
                                  text=True, check=False,
                                  stdin=subprocess.DEVNULL)
            return "unknown command" in done.stderr

        if not unknown(NOT_A_COMMAND):
            findings.append(f"the binary did not report {NOT_A_COMMAND!r} as an "
                            f"unknown command, so this probe cannot tell a "
                            f"handled command from an unhandled one and every "
                            f"answer below would be vacuous")
            return []

        answered = []
        for name in commands:
            if unknown(name):
                findings.append(f"the binary reports {name!r} as unknown, "
                                f"though main.go names it")
            else:
                answered.append(name)
        return answered
    finally:
        for leftover in binary.parent.glob("*"):
            leftover.unlink()
        binary.parent.rmdir()


def facts(findings):
    """Everything the block is generated from, derived once."""
    commands = probe(declared_commands(findings), findings)
    packages = module_packages(("list", "./..."))
    reachable = module_packages(("list", "-deps", "./cmd/spill-guard"))
    return {
        "commands": commands,
        "packages": [p for p in packages if p != "cmd/spill-guard"],
        "reachable": [p for p in reachable if p != "cmd/spill-guard"],
        "ruleset": RULESET.exists(),
        "wiring": WIRING.exists(),
    }


def rows(f):
    """The capability table, each row decided by one derived fact."""
    return [
        ("Scan a file or a buffer", "internal/scan" in f["reachable"]),
        ("Run as a Claude Code hook", f["wiring"] and "hook" in f["commands"]),
        ("Ship a ruleset", f["ruleset"]),
    ]


def prose(f):
    """The sentence under the table, which is where the nuance has to live.

    A bare "no" invites the reading that nothing is written. What is true is
    narrower and more useful: the packages exist and the binary cannot reach
    them, which is a wiring statement rather than an effort one.
    """
    commands = ", ".join(f"`{c}`" for c in f["commands"]) or "nothing"
    if not f["packages"]:
        return f"`spill-guard` builds and answers {commands}."
    unreached = [p for p in f["packages"] if p not in f["reachable"]]
    if not unreached:
        written = ", ".join(f"`{p}`" for p in f["packages"])
        return (f"`spill-guard` builds, answers {commands}, and reaches "
                f"{written}.")
    listed = ", ".join(f"`{p}`" for p in unreached)
    verb = "is" if len(unreached) == 1 else "are"
    reach = "it" if len(unreached) == 1 else "any of them"
    return (f"`spill-guard` builds and answers {commands}. {listed} {verb} "
            f"written and tested; the binary does not reach {reach} yet.")


def verdict(f):
    """The headline, derived rather than hand-flipped.

    Leaving this one line to a human is the same trap one line up: it is the
    sentence a reader acts on, it decays on exactly the change the table below
    tracks, and nothing would re-read it.
    """
    done = [label for label, ok in rows(f) if ok]
    if len(done) == len(rows(f)):
        return ("**Usable.** Every capability below is in place; see the "
                "install instructions.")
    if not done:
        return "**Not yet usable — installing it would get you nothing.**"
    return ("**Partly wired — not yet usable.** Some of what it needs is in "
            "place and some is not:")


def wrapped(text):
    """`text` at the width the rest of the file uses.

    A generated block that ignores the surrounding convention reads as machine
    output rather than as the document, and every hand edit around it then
    fights the generator.
    """
    return textwrap.wrap(text, width=WIDTH, break_long_words=False,
                         break_on_hyphens=False)


def table(f):
    lines = wrapped(verdict(f)) + ["", "| Capability | Today |", "|---|---|"]
    for label, ok in rows(f):
        lines.append(f"| {label} | {'yes' if ok else 'no'} |")
    lines.append("")
    lines.extend(wrapped(prose(f)))
    return "\n".join(lines)


def block(text):
    """(before, current, after) around the generated block, or None."""
    start = text.find(BEGIN)
    stop = text.find(END)
    if start < 0 or stop < 0 or stop < start:
        return None
    return (text[:start + len(BEGIN)],
            text[start + len(BEGIN):stop].strip("\n"),
            text[stop:])


def check(f, findings):
    text = DOC.read_text(encoding="utf-8")
    parts = block(text)
    if parts is None:
        findings.append(f"{DOC.relative_to(ROOT)} has no `status:begin` and "
                        f"`status:end` markers, so the status table is not "
                        f"generated and nothing keeps it current")
    elif parts[1] != table(f):
        findings.append(f"the status table in {DOC.relative_to(ROOT)} does not "
                        f"match the tree; `make status` rewrites it")
    return findings


def write(f):
    text = DOC.read_text(encoding="utf-8")
    parts = block(text)
    if parts is None:
        sys.exit(f"status: {DOC.relative_to(ROOT)} has no `status:begin` and "
                 f"`status:end` markers, so there is nothing to rewrite")
    fresh = table(f)
    if parts[1] == fresh:
        print(f"status: the table in {DOC.relative_to(ROOT)} is current")
        return 0
    DOC.write_text(f"{parts[0]}\n{fresh}\n{parts[2]}", encoding="utf-8")
    print(f"status: rewrote the table in {DOC.relative_to(ROOT)}")
    return 0


def main(argv):
    findings = []
    f = facts(findings)

    if argv[1:] == ["--check"]:
        check(f, findings)
        for entry in findings:
            print(f"status: {entry}", file=sys.stderr)
        if findings:
            print(f"\n{len(findings)} status problem(s). A status claim that "
                  f"goes stale silently reads as authoritative and is not.",
                  file=sys.stderr)
            return 1
        answered = ", ".join(f["commands"]) or "nothing"
        print(f"status: README matches the tree -- the binary answers "
              f"{answered} and reaches "
              f"{len(f['reachable'])} of {len(f['packages'])} package(s)")
        return 0

    if argv[1:]:
        sys.exit(f"status: unknown argument {argv[1]!r}; pass --check or nothing")

    # A rewrite still reports what it found wrong elsewhere: the generator can
    # fix its own block and cannot fix a usage text that disagrees with a switch.
    for entry in findings:
        print(f"status: {entry}", file=sys.stderr)
    rc = write(f)
    return 1 if findings else rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
