#!/usr/bin/env python3
"""Keep PRIVACY.md's account of what the hook reads and writes agreeing with
the tree.

PRIVACY.md is the page somebody reads while deciding whether to trust the tool,
and its list of what the hook reads was written from the design rather than
from the code. Every one of its five bullets was wrong -- a `Write` body the
hook never receives, a project ruleset nothing reads, `SPILL_GUARD_*` variables
the binary refuses to read by name -- and it shipped that way at v0.1.0 and
v0.2.0 with every gate green, because no gate read the file. Then #117 made the
scanner write a file, and a privacy page listing reads and omitting a write is
the same defect one direction over.

`check-status.py` is the shape: the block between the markers is generated, and
`--check` fails until the committed text is what the tree produces. What it
derives, and from where:

  * which events and tools the hook is delivered, from `hooks/hooks.json`. A
    tool the manifest names that this has no sentence for is a finding, and so
    is a sentence for a tool the manifest does not deliver -- that second
    direction is the `Write` bullet;
  * that on each of those surfaces the hook really opens the file it says it
    does, by driving the built binary: a planted corpus file behind a `Read`,
    a `Bash` reader and a prompt's `@` token must each block. The control is
    the same bytes in a `Write` body, which must not, since a hook that blocked
    everything would pass the three arms above and mean nothing;
  * the environment variables the binary reads, from the source of every
    package `go list -deps` says the binary reaches. Named reads are collected;
    a read this cannot name -- `os.Environ()`, a `Getenv` on a variable -- is a
    finding rather than a silent gap. The launcher is read the same way,
    because it is the other half of what `hooks.json` runs;
  * what the hook writes, by driving it in a sandboxed `HOME` and
    `XDG_STATE_HOME` and listing every file that appears. A call it could not
    scan must write exactly one, and every other call none.

What the drive cannot see, stated so nobody reads the green as more: a write to
an absolute path the binary never derived from its environment. The
environment derivation is what bounds that -- with `HOME`, `TMPDIR` and
`XDG_STATE_HOME` the only reads, a path outside the sandbox would have to be
hard-coded -- and a hard-coded path is a review finding, not a drive finding.

Needs Go on PATH, for `go list` and the build. Runs the binary on this host, so
the home-directory fallback it reports is the POSIX one; on Windows the same
call reads `USERPROFILE`, which this does not drive.
"""

import json
import os
import re
import shlex
import stat
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "PRIVACY.md"
MANIFEST = ROOT / "hooks" / "hooks.json"
LAUNCHER = ROOT / "hooks" / "run-spill-guard.cmd"
# The corpus file the precision gate already holds to exactly one finding. Read
# from the tree rather than written here, so no credential-shaped string lives
# in a script the hook would then block a reader of.
PLANTED = ROOT / "testdata" / "corpus" / "planted" / "aws-access-key-id.env"
MODULE = "github.com/karlkfi/claude-spill-guard"

# The width the rest of PRIVACY.md wraps at.
WIDTH = 79

BEGIN = ("<!-- privacy:begin -- generated by `make privacy`; "
         "derived from the tree and a driven binary, not hand-kept -->")
END = "<!-- privacy:end -->"

# What the hook reads on each surface the manifest can deliver. A key is an
# (event, tool) pair, with None where the event has no matcher and every call
# arrives. The sentence is hand-written; that it is TRUE is what the drives in
# reads() establish, and a key with no drive behind it would be the old page
# again.
SURFACES = {
    ("PreToolUse", "Bash"): "the command string, and the files its readers "
                            "are pointed at",
    ("PreToolUse", "Read"): "the `file_path`, and the file it names",
    ("UserPromptSubmit", None): "the prompt, and the files its `@` tokens name",
}

# Environment reads in Go source. NAMED is the shape this can report; ANY is
# every call that touches the environment, and a line matching ANY but not
# NAMED is a read this cannot name. IMPLIED are the stdlib calls that read a
# variable without naming it -- os.UserHomeDir reads HOME, and os.MkdirTemp
# with an empty dir reads TMPDIR through os.TempDir.
NAMED = re.compile(r'\bos\.(?:Getenv|LookupEnv)\(\s*"([A-Za-z_][A-Za-z0-9_]*)"\s*\)')
ANY = re.compile(r"\b(?:os|syscall)\.(?:Getenv|LookupEnv|Environ|ExpandEnv)\(")
IMPLIED = (
    (re.compile(r"\bos\.UserHomeDir\("), ("HOME",)),
    (re.compile(r"\bos\.UserConfigDir\("), ("HOME", "XDG_CONFIG_HOME")),
    (re.compile(r"\bos\.UserCacheDir\("), ("HOME", "XDG_CACHE_HOME")),
    (re.compile(r'\bos\.(?:TempDir\(|MkdirTemp\(\s*""|CreateTemp\(\s*"")'), ("TMPDIR",)),
)
LINE_COMMENT = re.compile(r"(?m)(^|\s)//.*$")
BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.S)

# The launcher is a cmd.exe half and a POSIX half in one file, so a variable is
# `%NAME%` in one and `$NAME` or `${NAME` in the other. A name the script
# assigns itself -- `DENY_MISSING=...` -- is not read from the environment, and
# neither is ERRORLEVEL, which is cmd.exe's own. `where` and `command -v` read
# PATH without spelling it.
SIGIL = re.compile(r"%([A-Z][A-Z0-9_]*)%|\$\{?([A-Z][A-Z0-9_]*)")
ASSIGNED = re.compile(r"(?m)^\s*([A-Z][A-Z0-9_]*)=")
CMD_OWN = {"ERRORLEVEL"}
LOOKUP = re.compile(r"(?m)^\s*where\s|\bcommand -v\s")
LAUNCHER_COMMENT = re.compile(r"(?mi)^\s*(?:REM\b|#).*$")


def go(*args):
    """`go` with args, or exit saying which call failed and why."""
    done = subprocess.run(("go",) + args, capture_output=True, text=True,
                          cwd=ROOT, check=False)
    if done.returncode != 0:
        sys.exit(f"privacy: `go {' '.join(args)}` exited {done.returncode}, so "
                 f"nothing below could be derived -- {done.stderr.strip()!r}")
    return done.stdout.split()


def wired(findings):
    """{event: [tool, ...]} from the manifest; [] where every call arrives."""
    doc = json.loads(MANIFEST.read_text(encoding="utf-8"))
    out = {}
    for event, entries in doc["hooks"].items():
        tools = set()
        for entry in entries:
            if "matcher" not in entry:
                continue
            for tool in entry["matcher"].split("|"):
                # A matcher is a regular expression, and this reads it as a
                # list of names. Anything else is a set this cannot enumerate.
                if not re.fullmatch(r"[A-Za-z]+", tool):
                    findings.append(f"{MANIFEST.relative_to(ROOT)} matches "
                                    f"{event} on {tool!r}, which is a pattern "
                                    f"rather than a tool name, so which tools "
                                    f"arrive cannot be listed here")
                    continue
                tools.add(tool)
        out[event] = sorted(tools)
    if not out:
        sys.exit(f"privacy: {MANIFEST.relative_to(ROOT)} wires no event, so "
                 f"the hook is delivered nothing and nothing below could fail")
    return out


def surfaces(events, findings):
    """The SURFACES keys the manifest delivers, in a stable order.

    Both directions, because both have been the defect: a delivered tool with
    no sentence is a read the page does not admit to, and a sentence for a tool
    the manifest never delivers is the `Write` body.
    """
    delivered = set()
    for event, tools in events.items():
        delivered.update((event, t) for t in tools or [None])
    for key in sorted(delivered - set(SURFACES), key=str):
        event, tool = key
        findings.append(f"{MANIFEST.relative_to(ROOT)} delivers "
                        f"{tool or 'every call'} on {event} and this script "
                        f"has no sentence for what the hook reads from it")
    for key in sorted(set(SURFACES) - delivered, key=str):
        event, tool = key
        findings.append(f"this script says what the hook reads from "
                        f"{tool or 'every call'} on {event}, and "
                        f"{MANIFEST.relative_to(ROOT)} never delivers it, so "
                        f"the page would describe a surface that does not "
                        f"arrive")
    return [k for k in SURFACES if k in delivered]


def strip_go_comments(src):
    return LINE_COMMENT.sub(r"\1", BLOCK_COMMENT.sub("", src))


def binary_env(findings):
    """Every environment variable the shipped binary reads, from its source.

    Over the packages the binary reaches and no others: a read in a test-only
    package is not a read the installed tool makes. The instrument is checked
    before it is trusted -- a regex that has stopped matching would report a
    binary that reads nothing, which is the answer this page would most like
    to give.
    """
    probe = 'x := os.Getenv("PROBE_VARIABLE")'
    if NAMED.findall(probe) != ["PROBE_VARIABLE"] or not ANY.search(probe):
        sys.exit("privacy: the environment-read patterns do not match their "
                 "own probe, so an empty result below would mean nothing")

    dirs = []
    for pkg in go("list", "-deps", "./cmd/spill-guard"):
        if pkg == MODULE:
            dirs.append(ROOT)
        elif pkg.startswith(MODULE + "/"):
            dirs.append(ROOT / pkg[len(MODULE) + 1:])
    files = sorted(f for d in dirs for f in d.glob("*.go")
                   if not f.name.endswith("_test.go"))
    if not files:
        sys.exit("privacy: `go list -deps ./cmd/spill-guard` reached no source "
                 "in this module, so there was nothing to read")

    names = set()
    for path in files:
        src = strip_go_comments(path.read_text(encoding="utf-8"))
        for lineno, line in enumerate(src.splitlines(), 1):
            names.update(NAMED.findall(line))
            for pattern, implied in IMPLIED:
                if pattern.search(line):
                    names.update(implied)
            if ANY.search(line) and not NAMED.search(line):
                findings.append(f"{path.relative_to(ROOT)}:{lineno} reads the "
                                f"environment in a form this cannot name, so "
                                f"the page cannot say what it reads")
    return sorted(names)


def launcher_env():
    """Every environment variable the launcher reads, from its text."""
    src = LAUNCHER_COMMENT.sub("", LAUNCHER.read_text(encoding="utf-8"))
    names = {a or b for a, b in SIGIL.findall(src)} - CMD_OWN
    names -= set(ASSIGNED.findall(src))
    if LOOKUP.search(src):
        names.add("PATH")
    return sorted(names)


class Sandbox:
    """A home directory, a state directory and a working directory the driven
    binary is pointed at, so what it writes lands where this can see it and
    nowhere a real session's log lives. #119 was a test suite writing to the
    real coverage log; this is the same care one level up."""

    def __init__(self, root):
        self.root = Path(root)
        self.home = self.root / "home"
        self.xdg = self.root / "xdg"
        self.cwd = self.root / "cwd"
        for d in (self.home, self.xdg, self.cwd):
            d.mkdir()
        self.binary = self.root / "spill-guard"
        self.planted = self.cwd / "planted.env"
        self.planted.write_bytes(PLANTED.read_bytes())
        self.quiet = self.cwd / "quiet.txt"
        self.quiet.write_text("nothing to find in here\n", encoding="utf-8")
        # UTF-32LE behind its mark: a declaration this build cannot decode, so
        # the call is the one shape that defers and writes a record.
        self.undecodable = self.cwd / "notes.utf32"
        self.undecodable.write_bytes(
            b"\xff\xfe\x00\x00" + "no credentials here\n".encode("utf-32-le"))

    def files(self):
        return {p.relative_to(self.root) for p in self.root.rglob("*")
                if p.is_file() and p != self.binary}

    def drive(self, payload, xdg=True):
        """(verdict, new files, stdout) for one hook invocation.

        The environment is the whole environment: nothing inherited, so a
        variable this host happens to export cannot steer the binary
        somewhere the snapshot does not cover.
        """
        env = {"HOME": str(self.home)}
        if xdg:
            env["XDG_STATE_HOME"] = str(self.xdg)
        before = self.files()
        done = subprocess.run([str(self.binary), "hook"], input=json.dumps(payload),
                              capture_output=True, text=True, env=env,
                              cwd=self.cwd, check=False)
        new = sorted(self.files() - before)
        return verdict(done.returncode, done.stdout), new, done.stdout


def verdict(rc, stdout):
    """What the hook decided, read the way Claude Code reads it."""
    if rc == 2:
        return "refused"
    if rc != 0:
        return f"exit {rc}"
    if not stdout.strip():
        return "allow"
    try:
        out = json.loads(stdout)
    except json.JSONDecodeError:
        return "unreadable stdout"
    if out.get("decision") == "block":
        return "block"
    if out.get("hookSpecificOutput", {}).get("permissionDecision") == "deny":
        return "block"
    return "allow"


READ = {"hook_event_name": "PreToolUse", "tool_name": "Read"}
BASH = {"hook_event_name": "PreToolUse", "tool_name": "Bash"}
OFFSET = re.compile(r"at byte (\d+) of")


def planted_line(sb, findings):
    """The line of the planted file a rule matches, or None.

    Learned from the binary rather than assumed: the fixture opens with comment
    lines, and the first drive of this probe carried one of those as the
    "secret" and reported the command-string surface unread. The block reason
    names a byte offset and nothing else, which is the whole of what this
    needs -- the line around it is what the text drives below carry.
    """
    got, _, stdout = sb.drive({**READ, "tool_input": {"file_path": str(sb.planted)}})
    m = OFFSET.search(stdout)
    if got != "block" or m is None:
        findings.append(f"a Read of the planted file came back {got} with no "
                        f"byte offset in the reason, so no drive below could "
                        f"carry the line a rule matches")
        return None
    text = PLANTED.read_text(encoding="utf-8")
    at = int(m.group(1))
    return text[text.rfind("\n", 0, at) + 1:text.find("\n", at)]


def payloads(sb, line):
    """One blocking drive per thing the SURFACES sentences claim is read, and
    two controls: the same bytes on a surface the hook does not scan, and a
    file with nothing in it on one it does."""
    prompt = {"hook_event_name": "UserPromptSubmit", "cwd": str(sb.cwd)}
    return {
        ("PreToolUse", "Bash"): [
            ("the command string",
             {**BASH, "tool_input": {"command": "echo " + shlex.quote(line)}}),
            ("a reader's file operand",
             {**BASH, "tool_input": {"command": "cat " + shlex.quote(str(sb.planted))}}),
        ],
        ("PreToolUse", "Read"): [
            ("the file it names", {**READ, "tool_input": {"file_path": str(sb.planted)}}),
        ],
        ("UserPromptSubmit", None): [
            ("the prompt text", {**prompt, "prompt": "deploy with " + line}),
            ("an `@` token's file", {**prompt, "prompt": "look at @planted.env"}),
        ],
    }, [
        ("Write", {"hook_event_name": "PreToolUse", "tool_name": "Write",
                   "tool_input": {"file_path": str(sb.cwd / "new.txt"),
                                  "content": line}}),
        ("Read", {**READ, "tool_input": {"file_path": str(sb.quiet)}}),
    ]


def reads(sb, keys, findings):
    """Drive every sentence the page will make, and the two controls."""
    line = planted_line(sb, findings)
    if line is None:
        return
    drives, controls = payloads(sb, line)
    for key in keys:
        event, tool = key
        for what, payload in drives[key]:
            got, new, _ = sb.drive(payload)
            if got != "block":
                findings.append(f"the page says the hook reads {what} on "
                                f"{tool or event} and the planted file behind "
                                f"it came back {got}, so that sentence is not "
                                f"true of this binary")
            if new:
                findings.append(f"a blocking {tool or event} call wrote "
                                f"{', '.join(map(str, new))}, and the page says "
                                f"only a call that could not be scanned writes")
    for tool, payload in controls:
        got, new, _ = sb.drive(payload)
        if got != "allow" and tool == "Write":
            findings.append(f"the same planted bytes in a {tool} body came back "
                            f"{got}, so this probe cannot tell a surface the "
                            f"hook reads from one it does not, and every block "
                            f"above would be vacuous")
        elif got != "allow":
            findings.append(f"a {tool} of a file with nothing in it came back "
                            f"{got}, so the blocks above are not about what was "
                            f"in the file")
        if new:
            findings.append(f"an allowing {tool} call wrote "
                            f"{', '.join(map(str, new))}")


def writes(sb, findings):
    """What a deferred call writes, with and without XDG_STATE_HOME."""
    payload = {"hook_event_name": "PreToolUse", "tool_name": "Read",
               "tool_input": {"file_path": str(sb.undecodable)}}
    out = {"keys": [], "mode": None, "names_path": False}
    for label, xdg, base in (("xdg", True, sb.xdg), ("home", False, sb.home)):
        got, new, _ = sb.drive(payload, xdg=xdg)
        if got != "allow":
            findings.append(f"a Read this build cannot decode came back {got} "
                            f"rather than deferring, so the write probe had "
                            f"nothing to observe")
        if len(new) != 1:
            findings.append(f"a deferred call with XDG_STATE_HOME "
                            f"{'set' if xdg else 'unset'} wrote "
                            f"{len(new)} file(s) ({', '.join(map(str, new))}); "
                            f"the page says one")
            out[label] = None
            continue
        path = sb.root / new[0]
        try:
            out[label] = str(path.relative_to(base))
        except ValueError:
            findings.append(f"a deferred call wrote {new[0]}, outside the "
                            f"{'state' if xdg else 'home'} directory the page "
                            f"says it writes under")
            out[label] = None
            continue
        record = json.loads(path.read_text(encoding="utf-8").splitlines()[-1])
        out["keys"] = list(record)
        out["mode"] = stat.S_IMODE(path.stat().st_mode)
        out["names_path"] = str(sb.undecodable) in record.get("reason", "")
        path.unlink()
    if out["keys"] and not out["names_path"]:
        findings.append("the coverage record does not name the path that went "
                        "unread, and the page says it does")
    return out


def facts(findings):
    """Everything the block is generated from, derived once."""
    events = wired(findings)
    keys = surfaces(events, findings)
    with tempfile.TemporaryDirectory(prefix="spill-guard-privacy-") as tmp:
        sb = Sandbox(tmp)
        go("build", "-o", str(sb.binary), "./cmd/spill-guard")
        reads(sb, keys, findings)
        written = writes(sb, findings)
    return {
        "surfaces": keys,
        "binary_env": binary_env(findings),
        "launcher_env": launcher_env(),
        "writes": written,
    }


def names(items):
    coded = [f"`{i}`" for i in items]
    if len(coded) <= 1:
        return "".join(coded) or "nothing"
    return ", ".join(coded[:-1]) + " and " + coded[-1]


def wrapped(text):
    return textwrap.wrap(text, width=WIDTH, break_long_words=False,
                         break_on_hyphens=False)


def table(f):
    lines = ["| Event | Tool | What the hook reads |", "|---|---|---|"]
    for event, tool in f["surfaces"]:
        lines.append(f"| `{event}` | {f'`{tool}`' if tool else 'every prompt'} "
                     f"| {SURFACES[(event, tool)]} |")
    lines.append("")
    lines.extend(wrapped(
        f"The binary reads {names(f['binary_env'])} from its environment, and "
        f"nothing else. The launcher, `hooks/run-spill-guard.cmd`, reads "
        f"{names(f['launcher_env'])}."))
    lines.append("")
    w = f["writes"]
    if w.get("xdg") and w.get("home"):
        lines.extend(wrapped(
            f"Driven in a sandboxed home directory, the hook wrote one file, "
            f"and only on a call it could not scan: `$XDG_STATE_HOME/{w['xdg']}`, "
            f"or `~/{w['home']}` when `XDG_STATE_HOME` is unset, created mode "
            f"`{w['mode']:04o}`. A record carries {names(w['keys'])}; the reason "
            f"names the path of what went unread, and none of its bytes."))
    else:
        lines.extend(wrapped("What the hook writes could not be derived; see "
                             "the findings `make privacy-drift` reports."))
    return "\n".join(lines)


def block(text):
    """(before, current, after) around the generated block, or None."""
    start = text.find(BEGIN)
    stop = text.find(END)
    if start < 0 or stop < 0 or stop < start:
        return None
    return (text[:start + len(BEGIN)],
            text[start + len(BEGIN):stop].strip("\n"),
            text[stop:])


def check(f, findings):
    text = DOC.read_text(encoding="utf-8")
    parts = block(text)
    if parts is None:
        findings.append(f"{DOC.relative_to(ROOT)} has no `privacy:begin` and "
                        f"`privacy:end` markers, so the list of what the hook "
                        f"reads is not generated and nothing keeps it current")
    elif parts[1] != table(f):
        findings.append(f"the generated block in {DOC.relative_to(ROOT)} does "
                        f"not match the tree; `make privacy` rewrites it")
    return findings


def write(f):
    text = DOC.read_text(encoding="utf-8")
    parts = block(text)
    if parts is None:
        sys.exit(f"privacy: {DOC.relative_to(ROOT)} has no `privacy:begin` and "
                 f"`privacy:end` markers, so there is nothing to rewrite")
    fresh = table(f)
    if parts[1] == fresh:
        print(f"privacy: the block in {DOC.relative_to(ROOT)} is current")
        return 0
    DOC.write_text(f"{parts[0]}\n{fresh}\n{parts[2]}", encoding="utf-8")
    print(f"privacy: rewrote the block in {DOC.relative_to(ROOT)}")
    return 0


def main(argv):
    findings = []
    f = facts(findings)

    if argv[1:] == ["--check"]:
        check(f, findings)
        for entry in findings:
            print(f"privacy: {entry}", file=sys.stderr)
        if findings:
            print(f"\n{len(findings)} privacy problem(s). A page that says what "
                  f"a tool reads and is wrong is read as authoritative anyway.",
                  file=sys.stderr)
            return 1
        print(f"privacy: PRIVACY.md matches the tree -- {len(f['surfaces'])} "
              f"surface(s) driven, the binary reads "
              f"{', '.join(f['binary_env'])}, and a deferred call writes "
              f"{f['writes'].get('xdg')}")
        return 0

    if argv[1:]:
        sys.exit(f"privacy: unknown argument {argv[1]!r}; pass --check or nothing")

    # A rewrite still reports what it found wrong elsewhere: the generator can
    # fix its own block and cannot fix a binary that reads what it cannot name.
    for entry in findings:
        print(f"privacy: {entry}", file=sys.stderr)
    rc = write(f)
    return 1 if findings else rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
