#!/usr/bin/env python3
"""Keep every copy of the gate list agreeing with the Makefile's.

A gate list wants to exist in three hand-kept copies -- what `make check` runs,
what the CI workflow's job list names, and whatever the docs enumerate. Every
gate-adding PR edits all three, concurrent branches conflict on all three, and
they drift anyway.

So there is one source of truth, `GATES` in the Makefile, and the consumers are
derived from it. That is the easy half. The half that matters is this check: a
derived list that can go stale silently is worse than honest copies, because it
reads as authoritative. What it asserts:

  * every gate has a description and a rule, so `list-gates` names it and
    `make <gate>` runs it;
  * the workflow's jobs are exactly the gates plus one mutation control each,
    with nothing extra and nothing missing;
  * each gate's job invokes `make <gate>`, so CI and a contributor's `make
    check` cannot run different commands under one name;
  * the generated table in CLAUDE.md matches the list.

Two modes. With no argument it rewrites the CLAUDE.md table -- the one consumer
a generator can write. `--check` asserts instead and exits 1 listing every
disagreement, so one run reports all of them. The workflow is never rewritten:
a job carries a runner, a checkout and a mutation control that no generator can
compose, so a job that has gone missing is a hand fix and the message says so.

The Makefile is read by asking make, not by parsing it. `go list` is the
toolchain's own answer to what gets linked, and `make print-gates` is make's
own answer to what the gate list holds; a second parser is a second opinion.
The workflow is read the same way, through the YAML parser in
tools/cmd/workflow: a job name this used to read with `^  ([A-Za-z0-9_-]+):$`
and a comment-stripping pass was simply not seen when it did not match, and
this check would then report agreement over a job list with an entry missing --
a gate can drop out of CI while the check that exists to prevent exactly that
stays green. Every job name in the file happened to match, so it was never
wrong; it was unable to be.
"""

import os
import re
import subprocess
import sys
from pathlib import Path

import workflow_model

ROOT = Path(__file__).resolve().parent.parent
WORKFLOW = ROOT / ".github" / "workflows" / "tests.yml"
DOC = ROOT / "CLAUDE.md"

BEGIN = "<!-- gates:begin -- generated by `make gates`; the list lives in the Makefile -->"
END = "<!-- gates:end -->"

# Every gate is paired with one, because a gate that has never failed is a
# claim rather than evidence. The suffix is the workflow's own convention.
CONTROL_SUFFIX = "-mutation-control"

# `make check` is the loop over the gates rather than a gate, so it is in no
# gate's name and the assertion below would read its control as an extra job.
# It is named here instead of derived, which is the whole cost of having one
# job the list does not generate. Its control breaks a gate that is not last
# and requires `check` to go red anyway -- the failure the loop can swallow.
RUNNER_JOBS = frozenset({"check-mutation-control"})

# What a gate name may look like. Anything else on print-gates' stdout is noise
# and is refused rather than absorbed -- see gates().
GATE_NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")

# GNU make 4.x announces `make[1]: Entering directory ...` on stdout when it
# believes it is a sub-make, and it believes that from MAKELEVEL in the
# environment -- which is exactly where this runs, since `make gate-drift` is
# what invokes this script. Measured 2026-08-22 on a runner: nine findings,
# every one of them a directory banner read as a gate name. make 3.81 does not
# print it, so no local run of any kind could have shown it.
#
# Three answers rather than one, because the parse has to survive whatever a
# future make prints: ask for silence, take away the reason it thinks it is a
# sub-make, and refuse a line that is not a gate.
MAKE_ENV_STRIP = ("MAKELEVEL", "MAKEFLAGS", "MFLAGS")


def make(*args):
    """Run make with nothing in the environment telling it it is a sub-make."""
    env = {k: v for k, v in os.environ.items() if k not in MAKE_ENV_STRIP}
    return subprocess.run(("make", "--no-print-directory") + args, cwd=ROOT,
                          check=False, capture_output=True, text=True, env=env)


def gates():
    """[(name, description)] in run order, from the Makefile. Never empty:
    a list that loaded nothing passes every assertion below."""
    result = make("print-gates")
    if result.returncode != 0:
        sys.exit(f"gates: `make print-gates` exited {result.returncode}:\n"
                 f"{result.stderr.strip()}")
    rows = []
    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        name, sep, desc = line.partition("\t")
        if not sep or not GATE_NAME_RE.match(name):
            sys.exit(f"gates: `make print-gates` wrote a line that is not a "
                     f"gate: {line!r}. Something in that invocation is writing "
                     f"to stdout -- a sub-make's directory banner is the usual "
                     f"one. Absorbing it would invent gates out of noise.")
        rows.append((name, desc.strip()))
    if not rows:
        sys.exit("gates: `make print-gates` named no gates, so nothing below "
                 "could have failed -- is GATES still set in the Makefile?")
    return rows


def has_rule(name):
    """Whether `make <name>` resolves to a rule. -n runs nothing."""
    return make("-n", name).returncode == 0


def jobs():
    """{job name: its `run:` commands}. Never empty: the parser exits rather
    than returning a document it could not read, which is the reason the gate
    list is not allowed to be empty either."""
    model = workflow_model.load([WORKFLOW])
    return {j["name"]: j["runs"]
            for j in model[str(WORKFLOW.relative_to(ROOT))]["jobs"]}


def table(rows):
    out = ["| Gate | What it covers |", "|---|---|"]
    out += [f"| `{name}` | {desc} |" for name, desc in rows]
    return "\n".join(out)


def block(text):
    """(before, current, after) around the generated table, or None."""
    start = text.find(BEGIN)
    stop = text.find(END)
    if start < 0 or stop < 0 or stop < start:
        return None
    return (text[:start + len(BEGIN)],
            text[start + len(BEGIN):stop].strip("\n"),
            text[stop:])


def check(rows):
    """Every disagreement, as a list of lines."""
    findings = []
    names = [name for name, _ in rows]

    for name, desc in rows:
        if not desc:
            findings.append(f"the Makefile sets no `{name}.desc`, so "
                            f"`make list-gates` names {name} and says nothing "
                            f"about it")
        if not has_rule(name):
            findings.append(f"{name} is in GATES with no rule to run it, so "
                            f"`make check` dies on it")

    found = jobs()
    want = set(names) | {n + CONTROL_SUFFIX for n in names} | RUNNER_JOBS
    for missing in sorted(want - set(found)):
        findings.append(f"{WORKFLOW.relative_to(ROOT)} has no `{missing}` job, "
                        f"so that gate runs nowhere in CI -- add the job by "
                        f"hand; this script does not write the workflow")
    for extra in sorted(set(found) - want):
        findings.append(f"{WORKFLOW.relative_to(ROOT)} runs a `{extra}` job "
                        f"that is in no gate's name, so `make check` does not "
                        f"cover it")

    for name in names:
        runs = found.get(name)
        if runs is None:
            continue
        # Against the commands the job runs, not against its block text: a
        # `make docs` inside an echo or a comment satisfied the old reading.
        if not any(re.search(rf"(?m)^\s*make\s+{re.escape(name)}\b", run)
                   for run in runs):
            findings.append(f"the `{name}` job does not invoke `make {name}`, "
                            f"so CI and `make check` can run different commands "
                            f"under one name")

    text = DOC.read_text(encoding="utf-8")
    parts = block(text)
    if parts is None:
        findings.append(f"{DOC.relative_to(ROOT)} carries no `gates:begin` / "
                        f"`gates:end` markers, so the gate table is not "
                        f"generated and nothing keeps it current")
    elif parts[1] != table(rows):
        findings.append(f"the gate table in {DOC.relative_to(ROOT)} does not "
                        f"match the list -- run `make gates`")
    return findings


def write(rows):
    text = DOC.read_text(encoding="utf-8")
    parts = block(text)
    if parts is None:
        sys.exit(f"gates: {DOC.relative_to(ROOT)} carries no `gates:begin` / "
                 f"`gates:end` markers to write between")
    before, current, after = parts
    fresh = table(rows)
    if current == fresh:
        print(f"gates: the table in {DOC.relative_to(ROOT)} is current")
        return 0
    DOC.write_text(f"{before}\n{fresh}\n{after}", encoding="utf-8")
    print(f"gates: rewrote the table in {DOC.relative_to(ROOT)}")
    return 0


def main(argv):
    rows = gates()
    if argv[1:] == ["--check"]:
        findings = check(rows)
        for entry in findings:
            print(f"gate drift: {entry}", file=sys.stderr)
        if findings:
            print(f"\n{len(findings)} disagreement(s) with GATES in the "
                  f"Makefile, which is the source of truth for all of them.",
                  file=sys.stderr)
            return 1
        print(f"gate drift: {len(rows)} gates, and every consumer agrees")
        return 0
    if argv[1:]:
        sys.exit(f"gates: unknown argument {argv[1]!r}; pass --check or nothing")
    return write(rows)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
